name: "Test pull request"
on: 
    pull_request: 
        types: [opened, reopened, synchronize]
jobs:
    check-infa:
        runs-on: ubuntu-latest
        steps:
            - name: job test
              run: echo "Hello world!"

            - name: Bot
              uses: JoseThen/comment-pr@v1.2.0
              with:
                comment: "Bot Test ${{secrets.GITHUB_TOKEN}}"
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}